./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat
./vaas-deploy-vm.py -t dako -g tomcat

